const mcmenu = [
  {
    id: "burgers",
    name: "Burgers",
    image: { src: "/js13-2/img/menu/bigmac.webp", alt: "burgers" },
    meals: [
      {
        id: "1",
        name: "BigMac",
        price: 180,
        image: { src: "/js13-2/img/menu/bigmac.webp", alt: "BigMac" },
        ingredImg: [
          { src: "/js13-2/img/menu/Ingredients/buns.webp", alt: "Bun" },
          { src: "/js13-2/img/menu/Ingredients/beef.webp", alt: "Beef" },
          { src: "/js13-2/img/menu/Ingredients//cheese.webp", alt: "Cheese" },
          { src: "/js13-2/img/menu/Ingredients/pickles.webp", alt: "Pickles" },
          { src: "/js13-2/img/menu/Ingredients/mustard.webp", alt: "Mustard" },
          { src: "/js13-2/img/menu/Ingredients/mayo.webp", alt: "Sauce" },
          { src: "/js13-2/img/menu/Ingredients/leafs.webp", alt: "Salat" },
        ],
        descript: "This is BigMac descript",
      },
      {
        id: "2",
        name: "Chessburger",
        price: 136,
        image: { src: "/js13-2/img/menu/cheesburger.webp", alt: "Chessburger" },
        ingredImg: [
            { src: "/js13-2/img/menu/Ingredients/buns.webp", alt: "Bun" },
            { src: "/js13-2/img/menu/Ingredients/beef.webp", alt: "Beef" },
            { src: "/js13-2/img/menu/Ingredients//cheese.webp", alt: "Cheese" },
            { src: "/js13-2/img/menu/Ingredients/pickles.webp", alt: "Pickles" },
            { src: "/js13-2/img/menu/Ingredients/ketchup.webp", alt: "Sauce" },
          ],
        descript: "This is Double Chessburger descript",
      },
      {
        id: "3",
        name: "McVeggie",
        price: 184,
        image: { src: "/js13-2/img/menu/mcvaggie.webp", alt: "McVaggie" },
        ingredImg: [
            { src: "/js13-2/img/menu/Ingredients/buns.webp", alt: "Bun" },
            { src: "/js13-2/img/menu/Ingredients/veggie.webp", alt: "Veggie" },
            { src: "/js13-2/img/menu/Ingredients//cheese.webp", alt: "Cheese" },
            { src: "/js13-2/img/menu/Ingredients/pickles.webp", alt: "Pickles" },
            { src: "/js13-2/img/menu/Ingredients/mayo.webp", alt: "Sauce" },
            { src: "/js13-2/img/menu/Ingredients/tomatos.webp", alt: "Tomato" },
          ],
        descript: "This is McVeggie descript",
      },
      {
        id: "4",
        name: "McChicken",
        price: 180,
        image: { src: "/js13-2/img/menu/mcchicken.webp", alt: "McChicken" },
        ingredImg: [
            { src: "/js13-2/img/menu/Ingredients/buns.webp", alt: "Bun" },
            { src: "/js13-2/img/menu/Ingredients/chicken.webp", alt: "Chicken" },
            { src: "/js13-2/img/menu/Ingredients//cheese.webp", alt: "Cheese" },
            { src: "/js13-2/img/menu/Ingredients/pickles.webp", alt: "Pickles" },
            { src: "/js13-2/img/menu/Ingredients/tomatos.webp", alt: "Tomato" },
            { src: "/js13-2/img/menu/Ingredients/mayo.webp", alt: "Mayo" },
          ],
        descript: "This is McChicken descript",
      },
    ],
  },

  {
    id: "sides",
    name: "Sides",
    image: { src: "/js13-2/img/menu/mcsalat.webp", alt: "sides" },
    meals: [
      {
        id: "1",
        name: "McSalat",
        price: 165,
        image: { src: "/js13-2/img/menu/mcsalat.webp", alt: "McSalat" },
        ingredImg: [],
        descript: "This is McSalat descript",
      },
      {
        id: "2",
        name: "McFries",
        price: 72,
        image: { src: "/js13-2/img/menu/fries.webp", alt: "McFries" },
        ingredImg: [],
        descript: "This is Fries descript",
      },
      {
        id: "3",
        name: "McNuggets",
        price: 148,
        image: { src: "/js13-2/img/menu/nuggets.webp", alt: "McNaggets" },
        ingredImg: [],
        descript: "This McNuggets descript",
      },
    ],
  },

  {
    id: "drinks",
    name: "Drinks",
    image: { src: "/js13-2/img/menu/cola.webp", alt: "drinks" },
    meals: [
      {
        id: "1",
        name: "Coca-Cola",
        price: 48,
        image: { src: "/js13-2/img/menu/cola.webp", alt: "Coca-Cola" },
        ingredImg: [],
        descript: "This is Coca-Cola descript",
      },
      {
        id: "2",
        name: "Orange Juice",
        price: 54,
        image: { src: "/js13-2/img/menu/juice.webp", alt: "Juice" },
        ingredImg: [],
        descript: "This is Orange Juice descript",
      },
      {
        id: "3",
        name: "Still water",
        price: 42,
        image: { src: "/js13-2/img/menu/water.webp", alt: "Water" },
        ingredImg: [],
        descript: "This Still water descript",
      },
    ],
  },
];
